In [1]:
import pandas as pd

In [2]:
s1 = pd.read_csv("../data/sample/sample_source1.tsv", sep='\t')
s2 = pd.read_csv("../data/sample/sample_source2.tsv", sep='\t')
s3 = pd.read_csv("../data/sample/sample_source3.tsv", sep='\t')
gt = pd.read_csv("../data/sample/sample_ground_truth.tsv", sep='\t')

In [3]:
s2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13550 entries, 0 to 13549
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   entity_id         13550 non-null  object
 1   business_name     13550 non-null  object
 2   business_address  13082 non-null  object
 3   country           13550 non-null  object
dtypes: object(4)
memory usage: 423.6+ KB

In [4]:
import sys
sys.path.append("..")

from src.normalization import normalize_pipeline

In [5]:
s1_normalized = normalize_pipeline(s1)
s2_normalized = normalize_pipeline(s2)
s3_normalized = normalize_pipeline(s3)

In [6]:
s1_normalized.head()

,entity_id,business_name,business_address,country,clean_name,clean_address,geo_block_key,phonetic_hash,search_document
0,S1-687925718,Couch and Ball Mckinley LLC,"6959 Alcala, Grand Prairie, TX",US,couch and ball mckinley llc,6959 alcala grand prairie tx,us_tx,KX ANT BL MKNL LK,couch and ball mckinley llc 6959 alcala grand ...
1,S1-833726872,Sahebganj Tree Ltd,"C/O Dilip Sahni, Panch Gaura, Vill-Nirpur, Sah...",India,sahebganj tree ltd,c o dilip sahni panch gaura vill nirpur sahebg...,india_bihar,SHBKNJ TR LTT,sahebganj tree ltd c o dilip sahni panch gaura...
2,S1-921126560,Heritage Charities,"784 Farmington Avenue, PA, Pottstown Borough",US,heritage charities,784 farmington ave pa pottstown borough,us_unknown,HRTJ XRTS,heritage charities 784 farmington ave pa potts...
3,S1-952049173,Nagpur Housing Private Limited,"600-A/12, Ratnadeep Housing Society, Byramji T...",India,nagpur housing ltd,600 a 12 ratnadeep housing society byramji tow...,india_maharashtra,NKPR HSNK LTT,nagpur housing ltd 600 a 12 ratnadeep housing ...
4,S1-161451865,Black Infra Private Limited,"E-49/5, First Flr Okhla, Industrial Area Phase...",India,black infra ltd,e 49 5 first flr okhla industrial area phase i...,india_delhi,BLK INFR LTT,black infra ltd e 49 5 first flr okhla industr...

In [7]:
s1_normalized['geo_block_key'].value_counts()

geo_block_key
us_unknown              1395
india_maharashtra        858
india_unknown            742
us_tx                    634
india_delhi              546
us_ny                    496
us_nc                    442
us_oh                    414
india_uttar_pradesh      353
us_il                    350
india_karnataka          336
us_ma                    285
us_tn                    284
india_tamil_nadu         279
india_telangana          278
india_gujarat            270
us_va                    265
us_az                    257
us_in                    249
india_west_bengal        244
us_wa                    203
us_md                    195
us_ca                    177
us_or                    157
us_mn                    154
us_wi                    152
india_rajasthan          146
india_haryana            146
india_kerala             138
us_al                    127
us_ky                    124
us_ar                    121
us_mo                    119
us_ok                    111
india_madhya_pradesh     108
us_ut                    100
us_ia                     99
india_bihar               90
us_wv                     83
us_ct                     79
us_ks                     79
india_orissa              77
india_andhra_pradesh      69
india_punjab              68
us_me                     51
us_mt                     50
Name: count, dtype: int64

In [8]:
from src.blocking import run_multi_index_generation

In [9]:
# Execute Index 1 and Index 2
candidate_pairs = run_multi_index_generation(s1_normalized, s2_normalized, top_k=15)

# Inspect the result
print(candidate_pairs.sort_values(by='bm25_text_score', ascending=False).head(10))

[US | TEXT] S1: 7252 | S2: 8068
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/8068 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/8068 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/8068 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/7252 [00:00<?, ?it/s]

     ...Processed 7252/7252
  -> Found 108780 pairs total in 1.39s.

[US | PHONETIC] S1: 7252 | S2: 8068
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/8068 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/8068 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/8068 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/7252 [00:00<?, ?it/s]

     ...Processed 7252/7252
  -> Found 108780 pairs total in 0.63s.

[INDIA | TEXT] S1: 4748 | S2: 5482
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/5482 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/5482 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/5482 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/4748 [00:00<?, ?it/s]

     ...Processed 4748/4748
  -> Found 71220 pairs total in 0.83s.

[INDIA | PHONETIC] S1: 4748 | S2: 5482
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/5482 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/5482 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/5482 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/4748 [00:00<?, ?it/s]

     ...Processed 4748/4748
  -> Found 71220 pairs total in 0.38s.

Merging global indices...
        s1_entity_id  s2_entity_id  bm25_text_score  bm25_phonetic_score
113238  S1-404904197  S2-483285102        56.907101             7.285493
70965   S1-291689772   S2-43961885        56.898838             4.189590
246428  S1-768542434  S2-861924707        37.829082             8.450515
237948  S1-746497359   S2-61947324        36.898369             5.193943
237929  S1-746497359  S2-128506843        36.898369             5.193943
102799  S1-374388852  S2-509116615        36.635078             7.780964
250150  S1-779032970  S2-501784863        36.057640             5.504806
4640    S1-113243666  S2-467976412        35.676167             7.364390
37182   S1-198445804  S2-323360342        35.619511             0.000000
146523   S1-49527993   S2-39902340        35.581829             6.358246

## Candidate pool using all 3 sources

In [10]:
import pandas as pd

def generate_global_candidate_pool(s1, s2, s3, top_k=15):
    """
    Executes the global BM25 indices across all source combinations 
    and standardizes the output into a single candidate pool.
    """
    print("="*40)
    print("STAGE 1: S1 vs S2")
    print("="*40)
    pairs_12 = run_multi_index_generation(s1, s2, top_k)
    
    print("\n" + "="*40)
    print("STAGE 2: S1 vs S3")
    print("="*40)
    pairs_13 = run_multi_index_generation(s1, s3, top_k)
    
    print("\n" + "="*40)
    print("STAGE 3: S2 vs S3")
    print("="*40)
    pairs_23 = run_multi_index_generation(s2, s3, top_k)
    
    # Standardize column names so they stack perfectly
    standard_columns = ['entity_A', 'entity_B', 'bm25_text_score', 'bm25_phonetic_score']
    
    if not pairs_12.empty: pairs_12.columns = standard_columns
    if not pairs_13.empty: pairs_13.columns = standard_columns
    if not pairs_23.empty: pairs_23.columns = standard_columns
    
    # Combine into a single master candidate pool
    print("\nMerging all cross-source candidate pairs...")
    master_pool = pd.concat([pairs_12, pairs_13, pairs_23], ignore_index=True)
    
    # Drop exact duplicates if multiple combinations caught the same pair
    master_pool = master_pool.drop_duplicates(subset=['entity_A', 'entity_B'])
    
    print(f"Total Unique Candidate Pairs Generated: {len(master_pool)}")
    return master_pool

# Execute the full pool generation
global_candidates_df = generate_global_candidate_pool(s1_normalized, s2_normalized, s3_normalized, top_k=15)

# Inspect the top matches
print(global_candidates_df.sort_values(by='bm25_text_score', ascending=False).head(10))

========================================
STAGE 1: S1 vs S2
========================================

[US | TEXT] S1: 7252 | S2: 8068
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/8068 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/8068 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/8068 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/7252 [00:00<?, ?it/s]

     ...Processed 7252/7252
  -> Found 108780 pairs total in 1.01s.

[US | PHONETIC] S1: 7252 | S2: 8068
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/8068 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/8068 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/8068 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/7252 [00:00<?, ?it/s]

     ...Processed 7252/7252
  -> Found 108780 pairs total in 0.63s.

[INDIA | TEXT] S1: 4748 | S2: 5482
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/5482 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/5482 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/5482 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/4748 [00:00<?, ?it/s]

     ...Processed 4748/4748
  -> Found 71220 pairs total in 0.80s.

[INDIA | PHONETIC] S1: 4748 | S2: 5482
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/5482 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/5482 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/5482 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/4748 [00:00<?, ?it/s]

     ...Processed 4748/4748
  -> Found 71220 pairs total in 0.37s.

Merging global indices...

========================================
STAGE 2: S1 vs S3
========================================

[US | TEXT] S1: 7252 | S2: 8401
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/8401 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/8401 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/8401 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/7252 [00:00<?, ?it/s]

     ...Processed 7252/7252
  -> Found 108780 pairs total in 0.99s.

[US | PHONETIC] S1: 7252 | S2: 8401
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/8401 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/8401 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/8401 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/7252 [00:00<?, ?it/s]

     ...Processed 7252/7252
  -> Found 108780 pairs total in 0.62s.

[INDIA | TEXT] S1: 4748 | S2: 5434
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/5434 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/5434 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/5434 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/4748 [00:00<?, ?it/s]

     ...Processed 4748/4748
  -> Found 71220 pairs total in 0.81s.

[INDIA | PHONETIC] S1: 4748 | S2: 5434
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/5434 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/5434 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/5434 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/4748 [00:00<?, ?it/s]

     ...Processed 4748/4748
  -> Found 71220 pairs total in 0.38s.

Merging global indices...

========================================
STAGE 3: S2 vs S3
========================================

[US | TEXT] S1: 8068 | S2: 8401
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/8401 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/8401 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/8401 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/8068 [00:00<?, ?it/s]

     ...Processed 8068/8068
  -> Found 121020 pairs total in 1.04s.

[US | PHONETIC] S1: 8068 | S2: 8401
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/8401 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/8401 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/8401 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/8068 [00:00<?, ?it/s]

     ...Processed 8068/8068
  -> Found 121020 pairs total in 0.65s.

[INDIA | TEXT] S1: 5482 | S2: 5434
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/5434 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/5434 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/5434 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/5482 [00:00<?, ?it/s]

     ...Processed 5482/5482
  -> Found 82230 pairs total in 0.89s.

[INDIA | PHONETIC] S1: 5482 | S2: 5434
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/5434 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/5434 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/5434 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/5482 [00:00<?, ?it/s]

     ...Processed 5482/5482
  -> Found 82230 pairs total in 0.49s.

Merging global indices...

Merging all cross-source candidate pairs...
Total Unique Candidate Pairs Generated: 1027855
            entity_A      entity_B  bm25_text_score  bm25_phonetic_score
113238  S1-404904197  S2-483285102        56.907101             7.285493
70965   S1-291689772   S2-43961885        56.898838             4.189590
401376  S1-291689772  S3-509594419        50.956989             3.530219
796858   S2-43961885  S3-509594419        50.956989             3.530219
654347  S1-986321350  S3-816108881        44.081314             5.331709
246428  S1-768542434  S2-861924707        37.829082             8.450515
367917  S1-198445804  S3-358555539        37.536079             0.000000
750581  S2-323360342  S3-358555539        37.536079             0.000000
357313  S1-171874760  S3-615657307        37.403778             6.088334
237929  S1-746497359  S2-128506843        36.898369             5.193943

## Validating the candidate pairs obtained

In [11]:


def validate_blocking_recall(candidates_df, ground_truth_df, gt_col_1='id1', gt_col_2='id2'):
    """
    Calculates what percentage of the ground truth matches were successfully 
    retrieved by our multi-index search engines.
    """
    # 1. Extract the true positive pairs from ground truth
    # We sort them alphabetically so (A, B) is treated the same as (B, A)
    print("Standardizing ground truth pairs...")
    true_pairs = set()
    for _, row in ground_truth_df.iterrows():
        pair = tuple(sorted([str(row[gt_col_1]), str(row[gt_col_2])]))
        true_pairs.add(pair)
        
    total_true = len(true_pairs)
    print(f"Total True Matches in Ground Truth: {total_true}")
    
    # 2. Extract the candidate pairs generated by our pipeline
    print("Standardizing generated candidate pairs...")
    candidate_pairs = set()
    for _, row in candidates_df.iterrows():
        pair = tuple(sorted([str(row['entity_A']), str(row['entity_B'])]))
        candidate_pairs.add(pair)
        
    total_candidates = len(candidate_pairs)
    print(f"Total Candidate Pairs Generated: {total_candidates}")
    
    # 3. Calculate Recall (Intersection)
    captured_pairs = true_pairs.intersection(candidate_pairs)
    captured_count = len(captured_pairs)
    
    recall = (captured_count / total_true) * 100 if total_true > 0 else 0
    
    print("\n" + "="*30)
    print("BLOCKING PIPELINE METRICS")
    print("="*30)
    print(f"-> True Matches Captured: {captured_count} / {total_true}")
    print(f"-> RECALL: {recall:.2f}%")
    
    # Calculate Reduction Ratio (How much we shrank the trillion-pair search space)
    # Assuming sample size of roughly ~10,000 per dataset for this run
    theoretical_max = 10000 * 10000 * 3 # Rough estimate for S1xS2, S1xS3, S2xS3
    reduction_ratio = 100 - ((total_candidates / theoretical_max) * 100)
    print(f"-> Search Space Reduction: ~{reduction_ratio:.4f}%")
    
    return captured_pairs, true_pairs - captured_pairs

# Execute validation (Change 'id1' and 'id2' to match your actual ground truth column names)
# Check g.columns if you aren't sure!
captured, missed = validate_blocking_recall(global_candidates_df, gt, gt_col_1='source1_entity_id', gt_col_2='matched_entity_ids')

Standardizing ground truth pairs...
Total True Matches in Ground Truth: 2000
Standardizing generated candidate pairs...
Total Candidate Pairs Generated: 1027855

==============================
BLOCKING PIPELINE METRICS
==============================
-> True Matches Captured: 131 / 2000
-> RECALL: 6.55%
-> Search Space Reduction: ~99.6574%

In [12]:
gt.head()

  source1_entity_id                                 matched_entity_ids
0      S1-777210964  S2-12029274,S2-407524980,S3-970714334,S3-71292...
1      S1-190133982             S2-523219173,S3-716445195,S3-986804760
2      S1-970131671                          S2-670035601,S3-392756625
3      S1-391999301  S2-742819060,S2-339356009,S2-233734305,S3-9388...
4      S1-435988542                                       S2-500704398

In [13]:
# 1. Check how many missed pairs actually exist in our current subset
s1_ids = set(s1_normalized['entity_id'])
s2_ids = set(s2_normalized['entity_id'])
s3_ids = set(s3_normalized['entity_id'])
all_available_ids = s1_ids | s2_ids | s3_ids

verifiable_misses = []
for pair in missed:
    # A pair is only "verifiable" if BOTH IDs are actually in the dataframes we processed
    if pair[0] in all_available_ids and pair[1] in all_available_ids:
        verifiable_misses.append(pair)

print(f"Total pairs missed: {len(missed)}")
print(f"Pairs missed where BOTH entities exist in our subset: {len(verifiable_misses)}")

# 2. Look at the text of 3 actual misses to see why BM25 failed
if len(verifiable_misses) > 0:
    print("\n" + "="*40)
    print("INSPECTING 3 MISSED PAIRS")
    print("="*40)
    
    # Create a quick lookup dictionary for names and addresses
    lookup_df = pd.concat([
        s1_normalized[['entity_id', 'business_name', 'business_address']],
        s2_normalized[['entity_id', 'business_name', 'business_address']],
        s3_normalized[['entity_id', 'business_name', 'business_address']]
    ]).set_index('entity_id')
    
    for i, pair in enumerate(verifiable_misses[:3]):
        id_A, id_B = pair
        print(f"\n--- Missed Pair {i+1} ---")
        print(f"Entity A ({id_A}): {lookup_df.loc[id_A, 'business_name']} | {lookup_df.loc[id_A, 'business_address']}")
        print(f"Entity B ({id_B}): {lookup_df.loc[id_B, 'business_name']} | {lookup_df.loc[id_B, 'business_address']}")

Total pairs missed: 1869
Pairs missed where BOTH entities exist in our subset: 0

In [14]:


# Load the full ground truth directly
g = pd.read_csv("../student_resource/dataset/train/train_ground_truth.tsv", sep='\t')

print("=== GROUND TRUTH PREVIEW ===")
print(g.head())

# Check the prefixes of the IDs in the ground truth
print("\n=== ID PREFIX DISTRIBUTION ===")
# Assuming the columns are actually 'id1' and 'id2'
if 'source1_entity_id' in g.columns and 'matched_entity_ids' in g.columns:
    print("source1_entity_id Prefixes:")
    print(g['source1_entity_id'].astype(str).str.split('-').str[0].value_counts())
    
    print("\nmatched_entity_ids Prefixes:")
    print(g['matched_entity_ids'].astype(str).str.split('-').str[0].value_counts())
else:
    print(f"Columns are actually: {g.columns.tolist()}")

=== GROUND TRUTH PREVIEW ===
  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

=== ID PREFIX DISTRIBUTION ===
source1_entity_id Prefixes:
source1_entity_id
S1    2206821
Name: count, dtype: int64

matched_entity_ids Prefixes:
matched_entity_ids
S2     1919076
S3      164498
nan     123247
Name: count, dtype: int64

## Updated Validation code

In [15]:
import pandas as pd

def validate_blocking_recall(candidates_df, ground_truth_df, s1_df, s2_df, s3_df):
    """
    Calculates fair recall by ensuring we only evaluate pairs where 
    both entities actually exist in the current sample dataframes.
    """
    print("Extracting available IDs from current sample subsets...")
    available_ids = set(s1_df['entity_id']).union(set(s2_df['entity_id'])).union(set(s3_df['entity_id']))
    
    print("Parsing raw ground truth clusters into verifiable pairs...")
    true_pairs = set()
    
    # Drop rows with NaN in matched_entity_ids
    valid_gt = ground_truth_df.dropna(subset=['matched_entity_ids'])
    
    for _, row in valid_gt.iterrows():
        s1_id = str(row['source1_entity_id']).strip()
        
        # Split the comma-separated string into a list of individual IDs
        matches = str(row['matched_entity_ids']).split(',')
        
        for match_id in matches:
            match_id = match_id.strip()
            if match_id:
                # ONLY count the pair if BOTH entities physically exist in our sample
                if s1_id in available_ids and match_id in available_ids:
                    pair = tuple(sorted([s1_id, match_id]))
                    true_pairs.add(pair)
                
    total_true = len(true_pairs)
    print(f"Total Verifiable True Matches to find: {total_true}")
    
    if total_true == 0:
        print("ERROR: No valid ground truth pairs exist in the current subsets.")
        return set(), set()

    print("Standardizing generated candidate pairs...")
    # Fast set comprehension for pairs
    candidate_pairs = set(
        tuple(sorted([str(a), str(b)])) 
        for a, b in zip(candidates_df['entity_A'], candidates_df['entity_B'])
    )
        
    total_candidates = len(candidate_pairs)
    print(f"Total Candidate Pairs Generated: {total_candidates}")
    
    # Calculate Recall
    captured_pairs = true_pairs.intersection(candidate_pairs)
    captured_count = len(captured_pairs)
    
    recall = (captured_count / total_true) * 100
    
    print("\n" + "="*30)
    print("BLOCKING PIPELINE METRICS")
    print("="*30)
    print(f"-> True Matches Captured: {captured_count} / {total_true}")
    print(f"-> RECALL: {recall:.2f}%")
    
    # Calculate Theoretical Search Space Reduction
    max_comps = (len(s1_df) * len(s2_df)) + (len(s1_df) * len(s3_df)) + (len(s2_df) * len(s3_df))
    reduction_ratio = 100 - ((total_candidates / max_comps) * 100) if max_comps > 0 else 0
    print(f"-> Search Space Reduction: ~{reduction_ratio:.4f}% (down from {max_comps:,} pairs)")
    
    return captured_pairs, true_pairs - candidate_pairs

# Execute validation on the new sample data
captured, missed = validate_blocking_recall(
    global_candidates_df, 
    g, 
    s1_normalized, 
    s2_normalized, 
    s3_normalized
)

Extracting available IDs from current sample subsets...
Parsing raw ground truth clusters into verifiable pairs...
Total Verifiable True Matches to find: 7447
Standardizing generated candidate pairs...
Total Candidate Pairs Generated: 1027855

==============================
BLOCKING PIPELINE METRICS
==============================
-> True Matches Captured: 7428 / 7447
-> RECALL: 99.74%
-> Search Space Reduction: ~99.8008% (down from 516,084,250 pairs)

## Validation after including index 3

In [16]:
import pandas as pd
from src.blocking import run_multi_index_generation, run_multi_source_geo_blocking

def generate_global_candidate_pool(s1, s2, s3, top_k=15):
    """Executes Index 1 & 2 across all pairs and standardizes columns."""
    print("="*40)
    print("STAGE 1-3: GLOBAL BM25 INDICES")
    print("="*40)
    
    pairs_12 = run_multi_index_generation(s1, s2, top_k)
    pairs_13 = run_multi_index_generation(s1, s3, top_k)
    pairs_23 = run_multi_index_generation(s2, s3, top_k)
    
    std_cols = ['entity_A', 'entity_B', 'bm25_text_score', 'bm25_phonetic_score']
    
    if not pairs_12.empty: pairs_12.columns = std_cols
    if not pairs_13.empty: pairs_13.columns = std_cols
    if not pairs_23.empty: pairs_23.columns = std_cols
    
    master_pool = pd.concat([pairs_12, pairs_13, pairs_23], ignore_index=True)
    return master_pool.drop_duplicates(subset=['entity_A', 'entity_B'])

# 1. Run Global Search (Index 1 & 2)
global_candidates_df = generate_global_candidate_pool(s1_normalized, s2_normalized, s3_normalized, top_k=15)

# 2. Run Local Geo Search (Index 3)
geo_candidates_df = run_multi_source_geo_blocking(s1_normalized, s2_normalized, s3_normalized, top_k=15)

# 3. Merge All Nets Together
print("\nMerging Local Geo matches into Master Candidate Pool...")
final_master_pool = pd.merge(
    global_candidates_df, 
    geo_candidates_df, 
    on=['entity_A', 'entity_B'], 
    how='outer'
).fillna(0.0)

print(f"Final Candidate Pool Size: {len(final_master_pool)}")

# 4. Final Validation check 
captured, missed = validate_blocking_recall(
    final_master_pool, 
    g, 
    s1_normalized, 
    s2_normalized, 
    s3_normalized
)

========================================
STAGE 1-3: GLOBAL BM25 INDICES
========================================

[US | TEXT] S1: 7252 | S2: 8068
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/8068 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/8068 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/8068 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/7252 [00:00<?, ?it/s]

     ...Processed 7252/7252
  -> Found 108780 pairs total in 0.98s.

[US | PHONETIC] S1: 7252 | S2: 8068
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/8068 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/8068 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/8068 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/7252 [00:00<?, ?it/s]

     ...Processed 7252/7252
  -> Found 108780 pairs total in 0.61s.

[INDIA | TEXT] S1: 4748 | S2: 5482
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/5482 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/5482 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/5482 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/4748 [00:00<?, ?it/s]

     ...Processed 4748/4748
  -> Found 71220 pairs total in 0.82s.

[INDIA | PHONETIC] S1: 4748 | S2: 5482
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/5482 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/5482 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/5482 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/4748 [00:00<?, ?it/s]

     ...Processed 4748/4748
  -> Found 71220 pairs total in 0.39s.

Merging global indices...

[US | TEXT] S1: 7252 | S2: 8401
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/8401 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/8401 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/8401 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/7252 [00:00<?, ?it/s]

     ...Processed 7252/7252
  -> Found 108780 pairs total in 1.00s.

[US | PHONETIC] S1: 7252 | S2: 8401
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/8401 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/8401 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/8401 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/7252 [00:00<?, ?it/s]

     ...Processed 7252/7252
  -> Found 108780 pairs total in 0.61s.

[INDIA | TEXT] S1: 4748 | S2: 5434
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/5434 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/5434 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/5434 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/4748 [00:00<?, ?it/s]

     ...Processed 4748/4748
  -> Found 71220 pairs total in 0.81s.

[INDIA | PHONETIC] S1: 4748 | S2: 5434
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/5434 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/5434 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/5434 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/4748 [00:00<?, ?it/s]

     ...Processed 4748/4748
  -> Found 71220 pairs total in 0.39s.

Merging global indices...

[US | TEXT] S1: 8068 | S2: 8401
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/8401 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/8401 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/8401 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/8068 [00:00<?, ?it/s]

     ...Processed 8068/8068
  -> Found 121020 pairs total in 1.04s.

[US | PHONETIC] S1: 8068 | S2: 8401
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/8401 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/8401 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/8401 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/8068 [00:00<?, ?it/s]

     ...Processed 8068/8068
  -> Found 121020 pairs total in 0.65s.

[INDIA | TEXT] S1: 5482 | S2: 5434
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/5434 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/5434 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/5434 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/5482 [00:00<?, ?it/s]

     ...Processed 5482/5482
  -> Found 82230 pairs total in 0.90s.

[INDIA | PHONETIC] S1: 5482 | S2: 5434
  -> Tokenizing S2 (Target) text...

Split strings:   0%|          | 0/5434 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/5434 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/5434 [00:00<?, ?it/s]

  -> Clearing RAM...
  -> Loading Index via mmap...
  -> Querying in chunks of 50000...

Split strings:   0%|          | 0/5482 [00:00<?, ?it/s]

     ...Processed 5482/5482
  -> Found 82230 pairs total in 0.48s.

Merging global indices...

========================================
STAGE 4: INDEX 3 (LOCAL GEO BLOCKING)
========================================

[S1 vs S2]
  -> Sweeping 42 shared geographic blocks...

[S1 vs S3]
  -> Sweeping 2 shared geographic blocks...

[S2 vs S3]
  -> Sweeping 9 shared geographic blocks...

Total Local Geo Pairs Generated: 185385

Merging Local Geo matches into Master Candidate Pool...
Final Candidate Pool Size: 1144794
Extracting available IDs from current sample subsets...
Parsing raw ground truth clusters into verifiable pairs...
Total Verifiable True Matches to find: 7447
Standardizing generated candidate pairs...
Total Candidate Pairs Generated: 1144794

==============================
BLOCKING PIPELINE METRICS
==============================
-> True Matches Captured: 7429 / 7447
-> RECALL: 99.76%
-> Search Space Reduction: ~99.7782% (down from 516,084,250 pairs)

In [17]:
import pandas as pd

def generate_baseline_submission(master_pool_df, s1_df, output_path="matching_results.tsv"):
    print("Generating baseline submission for the leaderboard...")
    
    # 1. Naive Thresholding (Surrogate for our future LightGBM model)
    # We only keep pairs with a reasonably strong signal to avoid tanking our precision.
    strong_matches = master_pool_df[
        (master_pool_df['bm25_text_score'] > 15.0) | 
        (master_pool_df['geo_ngram_score'] > 0.5)
    ].copy()
    
    # 2. Group by Source 1 ID and create the comma-separated list of S2/S3 matches
    grouped = strong_matches.groupby('entity_A')['entity_B'].apply(
        lambda x: ','.join(x.dropna().unique())
    ).reset_index()
    
    grouped = grouped.rename(columns={
        'entity_A': 'source1_entity_id', 
        'entity_B': 'matched_entity_ids'
    })
    
    # 3. Ensure ALL Source 1 entities are present in the final file
    # As required: "One row per Source 1 entity, empty list means no match"
    submission_df = pd.DataFrame({'source1_entity_id': s1_df['entity_id']})
    submission_df = pd.merge(submission_df, grouped, on='source1_entity_id', how='left')
    
    # 4. Fill missing matches with an empty string
    submission_df['matched_entity_ids'] = submission_df['matched_entity_ids'].fillna("")
    
    # 5. Export as TSV
    submission_df.to_csv(output_path, sep='\t', index=False)
    
    print(f"Saved submission to: {output_path}")
    print(f"Total rows in submission: {len(submission_df)} (Should match S1 row count)")
    print(f"S1 entities with at least one match: {len(submission_df[submission_df['matched_entity_ids'] != ''])}")
    
    return submission_df

# Generate the file using your full normalized S1 dataframe and the final candidate pool
# Note: You should run this on the full 'train' datasets, not just the 10k samples, 
# to get a real leaderboard score.
submission = generate_baseline_submission(
    final_master_pool, 
    s1_normalized, 
    output_path="matching_results.tsv"
)

Generating baseline submission for the leaderboard...
Saved submission to: matching_results.tsv
Total rows in submission: 12000 (Should match S1 row count)
S1 entities with at least one match: 2249

In [ ]:
## Executing Global Search