In [1]:
import pandas as pd

In [2]:
s1 = pd.read_csv("../data/sample/sample_source1.tsv", sep='\t')
s2 = pd.read_csv("../data/sample/sample_source2.tsv", sep='\t')
s3 = pd.read_csv("../data/sample/sample_source3.tsv", sep='\t')
gt = pd.read_csv("../data/sample/sample_ground_truth.tsv", sep='\t')

In [3]:
s2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10054 entries, 0 to 10053
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   entity_id         10054 non-null  object
 1   business_name     10054 non-null  object
 2   business_address  9722 non-null   object
 3   country           10054 non-null  object
dtypes: object(4)
memory usage: 314.3+ KB

In [4]:
import sys
sys.path.append("..")

from src.normalization import normalize_pipeline

In [5]:
s1_normalized = normalize_pipeline(s1)
s2_normalized = normalize_pipeline(s2)
s3_normalized = normalize_pipeline(s3)

In [6]:
s1_normalized.head()

,entity_id,business_name,business_address,country,clean_name,clean_address,geo_block_key,phonetic_hash,search_document
0,S1-962926747,Amen Traders Limited,"Egmore Benefit Society Building, Ii Floor No.2...",India,amen traders limited,egmore benefit society building ii floor no 25...,india_tamil_nadu,AMN TRTRS LMTT,amen traders limited egmore benefit society bu...
1,S1-839200959,Josefa's Express Lending LLC,"1751 Fisher Road, South Mahoning, PA",US,josefa s express lending llc,1751 fisher rd south mahoning pa,us_pa,JSF S EKSPRS LNTNK LK,josefa s express lending llc 1751 fisher rd so...
2,S1-791668499,Interfaith Committee VI,"1120 Delowe Drive, Unit 2206, Matthews, NC",US,interfaith committee vi,1120 delowe drive unit 2206 matthews nc,us_nc,INTRF0 KMT F,interfaith committee vi 1120 delowe drive unit...
3,S1-691815738,Catherine's Colonial Spa,"6742 Lunt Street, Chino, CA",US,catherine s colonial spa,6742 lunt st chino ca,us_ca,K0RN S KLNL SP,catherine s colonial spa 6742 lunt st chino ca
4,S1-978085452,EN India Pvt Ltd,"12/634, 3Rd Floor, St Joseph Arcade, Pala, Kot...",India,en india ltd,12 634 3rd floor st joseph arcade pala kottaya...,india_kerala,EN INT LTT,en india ltd 12 634 3rd floor st joseph arcade...

In [7]:
s1_normalized['geo_block_key'].value_counts()

geo_block_key
us_unknown              1241
india_maharashtra        910
india_unknown            734
us_tx                    602
india_delhi              582
us_ny                    488
us_nc                    447
us_oh                    422
us_il                    368
india_uttar_pradesh      366
india_karnataka          320
india_tamil_nadu         297
us_tn                    296
us_va                    282
us_ma                    276
india_telangana          265
india_gujarat            261
us_in                    242
india_west_bengal        239
us_wa                    215
us_az                    212
us_md                    183
india_kerala             170
us_mn                    167
us_al                    163
india_haryana            153
us_ca                    152
us_or                    150
india_rajasthan          145
us_wi                    142
us_ky                    135
us_mo                    126
us_ia                    115
us_ok                    115
us_ar                    109
us_ut                    103
india_bihar               94
india_madhya_pradesh      93
us_ct                     92
us_ks                     84
us_wv                     83
india_orissa              72
india_andhra_pradesh      72
us_nm                     60
us_pa                     57
us_mt                     50
india_punjab              50
Name: count, dtype: int64

In [8]:
from src.blocking import run_multi_index_generation

In [10]:
# Execute Index 1 and Index 2
candidate_pairs = run_multi_index_generation(s1_normalized, s2_normalized, top_k=15)

# Inspect the result
print(candidate_pairs.sort_values(by='bm25_text_score', ascending=False).head(10))

[INDIA | TEXT] S1: 4823 | S2: 4027
  -> Tokenizing text...

Split strings:   0%|          | 0/4027 [00:00<?, ?it/s]

Split strings:   0%|          | 0/4823 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/4027 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/4027 [00:00<?, ?it/s]

  -> Querying Top 15 matches...

BM25S Retrieve:   0%|          | 0/4823 [00:00<?, ?it/s]

  -> Mapping IDs...
  -> Found 72345 pairs total in 0.30s.

[INDIA | PHONETIC] S1: 4823 | S2: 4027
  -> Tokenizing text...

Split strings:   0%|          | 0/4027 [00:00<?, ?it/s]

Split strings:   0%|          | 0/4823 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/4027 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/4027 [00:00<?, ?it/s]

  -> Querying Top 15 matches...

BM25S Retrieve:   0%|          | 0/4823 [00:00<?, ?it/s]

  -> Mapping IDs...
  -> Found 72345 pairs total in 0.16s.

[US | TEXT] S1: 7177 | S2: 6027
  -> Tokenizing text...

Split strings:   0%|          | 0/6027 [00:00<?, ?it/s]

Split strings:   0%|          | 0/7177 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/6027 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/6027 [00:00<?, ?it/s]

  -> Querying Top 15 matches...

BM25S Retrieve:   0%|          | 0/7177 [00:00<?, ?it/s]

  -> Mapping IDs...
  -> Found 107655 pairs total in 0.41s.

[US | PHONETIC] S1: 7177 | S2: 6027
  -> Tokenizing text...

Split strings:   0%|          | 0/6027 [00:00<?, ?it/s]

Split strings:   0%|          | 0/7177 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/6027 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/6027 [00:00<?, ?it/s]

  -> Querying Top 15 matches...

BM25S Retrieve:   0%|          | 0/7177 [00:00<?, ?it/s]

  -> Mapping IDs...
  -> Found 107655 pairs total in 0.25s.

Merging global indices...
        s1_entity_id  s2_entity_id  bm25_text_score  bm25_phonetic_score
79611   S1-317394458  S2-464674986        36.724880             7.554364
243080  S1-763402416  S2-462074308        34.908421             3.871743
227727  S1-721795590  S2-834175295        30.709021             6.870881
236368  S1-746684756  S2-498269193        30.466774             6.357144
188132  S1-612558186  S2-190866988        29.898188             5.226541
34066   S1-193233802  S2-577123882        29.792381             4.326421
118425  S1-424242828  S2-709903978        28.947989             3.846308
10313   S1-126947501  S2-753997435        28.762899             6.151777
183838  S1-602468670  S2-139124957        26.833595             6.833516
310925  S1-945013098  S2-386121185        26.529905             0.000000

## Candidate pool using all 3 sources

In [11]:
import pandas as pd

def generate_global_candidate_pool(s1, s2, s3, top_k=15):
    """
    Executes the global BM25 indices across all source combinations 
    and standardizes the output into a single candidate pool.
    """
    print("="*40)
    print("STAGE 1: S1 vs S2")
    print("="*40)
    pairs_12 = run_multi_index_generation(s1, s2, top_k)
    
    print("\n" + "="*40)
    print("STAGE 2: S1 vs S3")
    print("="*40)
    pairs_13 = run_multi_index_generation(s1, s3, top_k)
    
    print("\n" + "="*40)
    print("STAGE 3: S2 vs S3")
    print("="*40)
    pairs_23 = run_multi_index_generation(s2, s3, top_k)
    
    # Standardize column names so they stack perfectly
    standard_columns = ['entity_A', 'entity_B', 'bm25_text_score', 'bm25_phonetic_score']
    
    if not pairs_12.empty: pairs_12.columns = standard_columns
    if not pairs_13.empty: pairs_13.columns = standard_columns
    if not pairs_23.empty: pairs_23.columns = standard_columns
    
    # Combine into a single master candidate pool
    print("\nMerging all cross-source candidate pairs...")
    master_pool = pd.concat([pairs_12, pairs_13, pairs_23], ignore_index=True)
    
    # Drop exact duplicates if multiple combinations caught the same pair
    master_pool = master_pool.drop_duplicates(subset=['entity_A', 'entity_B'])
    
    print(f"Total Unique Candidate Pairs Generated: {len(master_pool)}")
    return master_pool

# Execute the full pool generation
global_candidates_df = generate_global_candidate_pool(s1_normalized, s2_normalized, s3_normalized, top_k=15)

# Inspect the top matches
print(global_candidates_df.sort_values(by='bm25_text_score', ascending=False).head(10))

========================================
STAGE 1: S1 vs S2
========================================

[INDIA | TEXT] S1: 4823 | S2: 4027
  -> Tokenizing text...

Split strings:   0%|          | 0/4027 [00:00<?, ?it/s]

Split strings:   0%|          | 0/4823 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/4027 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/4027 [00:00<?, ?it/s]

  -> Querying Top 15 matches...

BM25S Retrieve:   0%|          | 0/4823 [00:00<?, ?it/s]

  -> Mapping IDs...
  -> Found 72345 pairs total in 0.31s.

[INDIA | PHONETIC] S1: 4823 | S2: 4027
  -> Tokenizing text...

Split strings:   0%|          | 0/4027 [00:00<?, ?it/s]

Split strings:   0%|          | 0/4823 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/4027 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/4027 [00:00<?, ?it/s]

  -> Querying Top 15 matches...

BM25S Retrieve:   0%|          | 0/4823 [00:00<?, ?it/s]

  -> Mapping IDs...
  -> Found 72345 pairs total in 0.17s.

[US | TEXT] S1: 7177 | S2: 6027
  -> Tokenizing text...

Split strings:   0%|          | 0/6027 [00:00<?, ?it/s]

Split strings:   0%|          | 0/7177 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/6027 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/6027 [00:00<?, ?it/s]

  -> Querying Top 15 matches...

BM25S Retrieve:   0%|          | 0/7177 [00:00<?, ?it/s]

  -> Mapping IDs...
  -> Found 107655 pairs total in 0.43s.

[US | PHONETIC] S1: 7177 | S2: 6027
  -> Tokenizing text...

Split strings:   0%|          | 0/6027 [00:00<?, ?it/s]

Split strings:   0%|          | 0/7177 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/6027 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/6027 [00:00<?, ?it/s]

  -> Querying Top 15 matches...

BM25S Retrieve:   0%|          | 0/7177 [00:00<?, ?it/s]

  -> Mapping IDs...
  -> Found 107655 pairs total in 0.25s.

Merging global indices...

========================================
STAGE 2: S1 vs S3
========================================

[INDIA | TEXT] S1: 4823 | S2: 4035
  -> Tokenizing text...

Split strings:   0%|          | 0/4035 [00:00<?, ?it/s]

Split strings:   0%|          | 0/4823 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/4035 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/4035 [00:00<?, ?it/s]

  -> Querying Top 15 matches...

BM25S Retrieve:   0%|          | 0/4823 [00:00<?, ?it/s]

  -> Mapping IDs...
  -> Found 72345 pairs total in 0.28s.

[INDIA | PHONETIC] S1: 4823 | S2: 4035
  -> Tokenizing text...

Split strings:   0%|          | 0/4035 [00:00<?, ?it/s]

Split strings:   0%|          | 0/4823 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/4035 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/4035 [00:00<?, ?it/s]

  -> Querying Top 15 matches...

BM25S Retrieve:   0%|          | 0/4823 [00:00<?, ?it/s]

  -> Mapping IDs...
  -> Found 72345 pairs total in 0.18s.

[US | TEXT] S1: 7177 | S2: 6026
  -> Tokenizing text...

Split strings:   0%|          | 0/6026 [00:00<?, ?it/s]

Split strings:   0%|          | 0/7177 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/6026 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/6026 [00:00<?, ?it/s]

  -> Querying Top 15 matches...

BM25S Retrieve:   0%|          | 0/7177 [00:00<?, ?it/s]

  -> Mapping IDs...
  -> Found 107655 pairs total in 0.44s.

[US | PHONETIC] S1: 7177 | S2: 6026
  -> Tokenizing text...

Split strings:   0%|          | 0/6026 [00:00<?, ?it/s]

Split strings:   0%|          | 0/7177 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/6026 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/6026 [00:00<?, ?it/s]

  -> Querying Top 15 matches...

BM25S Retrieve:   0%|          | 0/7177 [00:00<?, ?it/s]

  -> Mapping IDs...
  -> Found 107655 pairs total in 0.26s.

Merging global indices...

========================================
STAGE 3: S2 vs S3
========================================

[INDIA | TEXT] S1: 4027 | S2: 4035
  -> Tokenizing text...

Split strings:   0%|          | 0/4035 [00:00<?, ?it/s]

Split strings:   0%|          | 0/4027 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/4035 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/4035 [00:00<?, ?it/s]

  -> Querying Top 15 matches...

BM25S Retrieve:   0%|          | 0/4027 [00:00<?, ?it/s]

  -> Mapping IDs...
  -> Found 60405 pairs total in 0.23s.

[INDIA | PHONETIC] S1: 4027 | S2: 4035
  -> Tokenizing text...

Split strings:   0%|          | 0/4035 [00:00<?, ?it/s]

Split strings:   0%|          | 0/4027 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/4035 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/4035 [00:00<?, ?it/s]

  -> Querying Top 15 matches...

BM25S Retrieve:   0%|          | 0/4027 [00:00<?, ?it/s]

  -> Mapping IDs...
  -> Found 60405 pairs total in 0.19s.

[US | TEXT] S1: 6027 | S2: 6026
  -> Tokenizing text...

Split strings:   0%|          | 0/6026 [00:00<?, ?it/s]

Split strings:   0%|          | 0/6027 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/6026 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/6026 [00:00<?, ?it/s]

  -> Querying Top 15 matches...

BM25S Retrieve:   0%|          | 0/6027 [00:00<?, ?it/s]

  -> Mapping IDs...
  -> Found 90405 pairs total in 0.33s.

[US | PHONETIC] S1: 6027 | S2: 6026
  -> Tokenizing text...

Split strings:   0%|          | 0/6026 [00:00<?, ?it/s]

Split strings:   0%|          | 0/6027 [00:00<?, ?it/s]

  -> Building BM25 Search Engine...

BM25S Count Tokens:   0%|          | 0/6026 [00:00<?, ?it/s]

BM25S Compute Scores:   0%|          | 0/6026 [00:00<?, ?it/s]

  -> Querying Top 15 matches...

BM25S Retrieve:   0%|          | 0/6027 [00:00<?, ?it/s]

  -> Mapping IDs...
  -> Found 90405 pairs total in 0.22s.

Merging global indices...

Merging all cross-source candidate pairs...
Total Unique Candidate Pairs Generated: 933581
            entity_A      entity_B  bm25_text_score  bm25_phonetic_score
79611   S1-317394458  S2-464674986        36.724880             7.554364
243080  S1-763402416  S2-462074308        34.908421             3.871743
446525  S1-417290047  S3-321064506        32.568581             2.945133
559299  S1-727095215  S3-205244567        31.522064             5.120560
227727  S1-721795590  S2-834175295        30.709021             6.870881
236368  S1-746684756  S2-498269193        30.466774             6.357144
188132  S1-612558186  S2-190866988        29.898188             5.226541
34066   S1-193233802  S2-577123882        29.792381             4.326421
118425  S1-424242828  S2-709903978        28.947989             3.846308
417031  S1-337289417  S3-611005011        28.781012             0.000000

## Validating the candidate pairs obtained

In [12]:


def validate_blocking_recall(candidates_df, ground_truth_df, gt_col_1='id1', gt_col_2='id2'):
    """
    Calculates what percentage of the ground truth matches were successfully 
    retrieved by our multi-index search engines.
    """
    # 1. Extract the true positive pairs from ground truth
    # We sort them alphabetically so (A, B) is treated the same as (B, A)
    print("Standardizing ground truth pairs...")
    true_pairs = set()
    for _, row in ground_truth_df.iterrows():
        pair = tuple(sorted([str(row[gt_col_1]), str(row[gt_col_2])]))
        true_pairs.add(pair)
        
    total_true = len(true_pairs)
    print(f"Total True Matches in Ground Truth: {total_true}")
    
    # 2. Extract the candidate pairs generated by our pipeline
    print("Standardizing generated candidate pairs...")
    candidate_pairs = set()
    for _, row in candidates_df.iterrows():
        pair = tuple(sorted([str(row['entity_A']), str(row['entity_B'])]))
        candidate_pairs.add(pair)
        
    total_candidates = len(candidate_pairs)
    print(f"Total Candidate Pairs Generated: {total_candidates}")
    
    # 3. Calculate Recall (Intersection)
    captured_pairs = true_pairs.intersection(candidate_pairs)
    captured_count = len(captured_pairs)
    
    recall = (captured_count / total_true) * 100 if total_true > 0 else 0
    
    print("\n" + "="*30)
    print("BLOCKING PIPELINE METRICS")
    print("="*30)
    print(f"-> True Matches Captured: {captured_count} / {total_true}")
    print(f"-> RECALL: {recall:.2f}%")
    
    # Calculate Reduction Ratio (How much we shrank the trillion-pair search space)
    # Assuming sample size of roughly ~10,000 per dataset for this run
    theoretical_max = 10000 * 10000 * 3 # Rough estimate for S1xS2, S1xS3, S2xS3
    reduction_ratio = 100 - ((total_candidates / theoretical_max) * 100)
    print(f"-> Search Space Reduction: ~{reduction_ratio:.4f}%")
    
    return captured_pairs, true_pairs - captured_pairs

# Execute validation (Change 'id1' and 'id2' to match your actual ground truth column names)
# Check g.columns if you aren't sure!
captured, missed = validate_blocking_recall(global_candidates_df, gt, gt_col_1='source1_entity_id', gt_col_2='matched_entity_ids')

Standardizing ground truth pairs...
Total True Matches in Ground Truth: 2000
Standardizing generated candidate pairs...
Total Candidate Pairs Generated: 933581

==============================
BLOCKING PIPELINE METRICS
==============================
-> True Matches Captured: 115 / 2000
-> RECALL: 5.75%
-> Search Space Reduction: ~99.6888%

In [13]:
gt.head()

  source1_entity_id                                 matched_entity_ids
0      S1-384734976  S2-685146894,S2-908470079,S3-109845102,S3-1764...
1      S1-574038342             S2-133116927,S2-180265553,S2-201976425
2      S1-189408085                                                NaN
3      S1-797774718                          S2-151469064,S3-994706509
4      S1-729164458             S2-619382517,S2-949886625,S3-532795614

In [14]:
# 1. Check how many missed pairs actually exist in our current subset
s1_ids = set(s1_normalized['entity_id'])
s2_ids = set(s2_normalized['entity_id'])
s3_ids = set(s3_normalized['entity_id'])
all_available_ids = s1_ids | s2_ids | s3_ids

verifiable_misses = []
for pair in missed:
    # A pair is only "verifiable" if BOTH IDs are actually in the dataframes we processed
    if pair[0] in all_available_ids and pair[1] in all_available_ids:
        verifiable_misses.append(pair)

print(f"Total pairs missed: {len(missed)}")
print(f"Pairs missed where BOTH entities exist in our subset: {len(verifiable_misses)}")

# 2. Look at the text of 3 actual misses to see why BM25 failed
if len(verifiable_misses) > 0:
    print("\n" + "="*40)
    print("INSPECTING 3 MISSED PAIRS")
    print("="*40)
    
    # Create a quick lookup dictionary for names and addresses
    lookup_df = pd.concat([
        s1_normalized[['entity_id', 'business_name', 'business_address']],
        s2_normalized[['entity_id', 'business_name', 'business_address']],
        s3_normalized[['entity_id', 'business_name', 'business_address']]
    ]).set_index('entity_id')
    
    for i, pair in enumerate(verifiable_misses[:3]):
        id_A, id_B = pair
        print(f"\n--- Missed Pair {i+1} ---")
        print(f"Entity A ({id_A}): {lookup_df.loc[id_A, 'business_name']} | {lookup_df.loc[id_A, 'business_address']}")
        print(f"Entity B ({id_B}): {lookup_df.loc[id_B, 'business_name']} | {lookup_df.loc[id_B, 'business_address']}")

Total pairs missed: 1885
Pairs missed where BOTH entities exist in our subset: 0

In [15]:


# Load the full ground truth directly
g = pd.read_csv("../student_resource/dataset/train/train_ground_truth.tsv", sep='\t')

print("=== GROUND TRUTH PREVIEW ===")
print(g.head())

# Check the prefixes of the IDs in the ground truth
print("\n=== ID PREFIX DISTRIBUTION ===")
# Assuming the columns are actually 'id1' and 'id2'
if 'source1_entity_id' in g.columns and 'matched_entity_ids' in g.columns:
    print("source1_entity_id Prefixes:")
    print(g['source1_entity_id'].astype(str).str.split('-').str[0].value_counts())
    
    print("\nmatched_entity_ids Prefixes:")
    print(g['matched_entity_ids'].astype(str).str.split('-').str[0].value_counts())
else:
    print(f"Columns are actually: {g.columns.tolist()}")

=== GROUND TRUTH PREVIEW ===
  source1_entity_id                                 matched_entity_ids
0         S1-965667  S2-681193310,S2-743505751,S3-775321672,S3-1129...
1       S1-55344266  S2-249013014,S2-197070651,S3-478195123,S3-3843...
2      S1-343815751             S2-790675320,S2-479876582,S3-878454467
3      S1-656753428              S2-153058913,S2-24659151,S3-679606215
4      S1-102811957  S2-478959098,S2-553508714,S2-625774905,S3-7280...

=== ID PREFIX DISTRIBUTION ===
source1_entity_id Prefixes:
source1_entity_id
S1    2206821
Name: count, dtype: int64

matched_entity_ids Prefixes:
matched_entity_ids
S2     1919076
S3      164498
nan     123247
Name: count, dtype: int64

## Updated Validation code

In [16]:
import pandas as pd

def validate_blocking_recall(candidates_df, ground_truth_df, s1_df, s2_df, s3_df):
    """
    Calculates fair recall by ensuring we only evaluate pairs where 
    both entities actually exist in the current sample dataframes.
    """
    print("Extracting available IDs from current sample subsets...")
    available_ids = set(s1_df['entity_id']).union(set(s2_df['entity_id'])).union(set(s3_df['entity_id']))
    
    print("Parsing raw ground truth clusters into verifiable pairs...")
    true_pairs = set()
    
    # Drop rows with NaN in matched_entity_ids
    valid_gt = ground_truth_df.dropna(subset=['matched_entity_ids'])
    
    for _, row in valid_gt.iterrows():
        s1_id = str(row['source1_entity_id']).strip()
        
        # Split the comma-separated string into a list of individual IDs
        matches = str(row['matched_entity_ids']).split(',')
        
        for match_id in matches:
            match_id = match_id.strip()
            if match_id:
                # ONLY count the pair if BOTH entities physically exist in our sample
                if s1_id in available_ids and match_id in available_ids:
                    pair = tuple(sorted([s1_id, match_id]))
                    true_pairs.add(pair)
                
    total_true = len(true_pairs)
    print(f"Total Verifiable True Matches to find: {total_true}")
    
    if total_true == 0:
        print("ERROR: No valid ground truth pairs exist in the current subsets.")
        return set(), set()

    print("Standardizing generated candidate pairs...")
    # Fast set comprehension for pairs
    candidate_pairs = set(
        tuple(sorted([str(a), str(b)])) 
        for a, b in zip(candidates_df['entity_A'], candidates_df['entity_B'])
    )
        
    total_candidates = len(candidate_pairs)
    print(f"Total Candidate Pairs Generated: {total_candidates}")
    
    # Calculate Recall
    captured_pairs = true_pairs.intersection(candidate_pairs)
    captured_count = len(captured_pairs)
    
    recall = (captured_count / total_true) * 100
    
    print("\n" + "="*30)
    print("BLOCKING PIPELINE METRICS")
    print("="*30)
    print(f"-> True Matches Captured: {captured_count} / {total_true}")
    print(f"-> RECALL: {recall:.2f}%")
    
    # Calculate Theoretical Search Space Reduction
    max_comps = (len(s1_df) * len(s2_df)) + (len(s1_df) * len(s3_df)) + (len(s2_df) * len(s3_df))
    reduction_ratio = 100 - ((total_candidates / max_comps) * 100) if max_comps > 0 else 0
    print(f"-> Search Space Reduction: ~{reduction_ratio:.4f}% (down from {max_comps:,} pairs)")
    
    return captured_pairs, true_pairs - candidate_pairs

# Execute validation on the new sample data
captured, missed = validate_blocking_recall(
    global_candidates_df, 
    g, 
    s1_normalized, 
    s2_normalized, 
    s3_normalized
)

Extracting available IDs from current sample subsets...
Parsing raw ground truth clusters into verifiable pairs...
Total Verifiable True Matches to find: 209
Standardizing generated candidate pairs...
Total Candidate Pairs Generated: 933581

==============================
BLOCKING PIPELINE METRICS
==============================
-> True Matches Captured: 208 / 209
-> RECALL: 99.52%
-> Search Space Reduction: ~99.7274% (down from 342,533,294 pairs)